---
title: "deserts.Rmd"
output: html_document
date: '2022-07-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(jsonlite)
library(ggthemes)
```

This graphic will show the locations of food deserts in Cook County, IL. Food deserts are a significant food security issue. Food deserts are areas that lack grocery stores, which makes it difficult for people to access fresh, healthy food and ingredients.

```{r cleaning}
json_url <- "https://services1.arcgis.com/RLQu0rK7h4kbsBq5/arcgis/rest/services/Store_Locations/FeatureServer/0/query?where=State%20%3D%20'IL'%20AND%20County%20%3D%20'COOK'&outFields=Store_Name,State,County,Longitude,Latitude&outSR=4326&f=json"
county_stores <- fromJSON(json_url)
county_stores <- county_stores$features$attributes

county_map <- get_acs(geography="tract",
        variables="B06012_002",
        year=2018,
        state="Illinois",
        county="Cook County",
        geometry = TRUE,
        summary_var="B02001_001") |> 
    mutate(Amount = 100 * estimate/summary_est)
```

```{r map}
county_map |> 
  ggplot(mapping=aes(fill= Amount, color=Amount)) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  geom_point(data=county_stores,
             inherit.aes = FALSE,
             size=0.5,
             aes(x=Longitude,
                 y=Latitude)) +
  theme_void() +
  labs(title="Grocery stores and poverty in Cook County",
       fill = "Percent of residents \nunder poverty line",
       color="Percent of residents \nunder poverty line",
       caption = "SNAP Retailer Locator, USDA Food and Nutrition Service",
       subtitle="Food deserts are found in low-income areas")
```

