---
title: "tworaces.Rmd"
output: html_document
date: '2022-07-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
library(readr)
```

```{r get_variables}
load_variables(2018, "acs5") |> filter(concept == "RACE")
```

```{r}
continental <- state.name[! state.name %in% c("Alaska", "Hawaii")]
races <- get_acs(geography = "tract",
        variables = "B02001_008",
        year = 2018, 
        state = continental,
        geometry = TRUE,
        summary_var = "B02001_001") |> 
    mutate(Percent = estimate/summary_est * 100)
```

```{r map}
races_graph <- races |> 
  mutate(Percent = 100 * estimate/summary_est) |> 
  ggplot(aes(fill = Percent)) +
  geom_sf(size=0.003) +
  scale_fill_viridis_c(direction = -1,
                       option = "inferno") + 
  theme_void() +
  labs(title="Percent of people who identify with two or more races, by census tract",
       caption = "Source: American Community Survey 2014-2018")
```

```{r make_rds}
write_rds(x=races_graph, "races_map.rds")
```

```{r}
read_rds("races_map.rds")
```

```{r rds}
write_rds(x=races_graph, "races_map.rds")
```
